export const ApiConstants = {
  GetTenantInfo: "api/v1/tenantInfo/getTenantInfo",
  SetTenantInfo: "api/v1/tenantInfo/setTenantInfo",
  GetTenantFormData: "api/v1/tenantInfo/getTenantFormData",
  AddTenant: "api/v1/tenantInfo/addTenant",
  UpdateTenantStep: "api/v1/tenantInfo/updateTenantStep",
  CreateFonts: "/api/v1/fontsUpload/createFonts",
  GetAllTenants: "api/v1/tenantInfo/getAllTenants",
  RemoveTenant: "api/v1/tenantInfo/removeTenant",
  DownloadTenantFolder: "api/v1/tenantInfo/downloadTenantFolder",
  GetTenantIdByName: "api/v1/tenantInfo/getTenantIdByName",
  FileConfigsUpload: "api/v1/fileConfigs/fileConfigsUpload",
  DeleteFile: "api/v1/fileConfigs/deleteFile",
  CreateColors: "/api/v1/colorStep/createColors",
  IconGenerator: "/api/v1/iconGenerator/iconGenerator",
  Login: "/api/v1/user/login",
};
