import { getTenantStyle } from "@/themes/colors";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import ClientProvider from "./providers/clientProvider";
import ServerProvider from "./providers/serverProvider";

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tenantData = await getTenantStyle();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${quicksand.className} scroll-smooth bg-surface text-secondary-text antialiased h-screen`}
      >
        {tenantData.isColor && <style>{tenantData.color}</style>}
        <ServerProvider>
          <ClientProvider>{children}</ClientProvider>
        </ServerProvider>
      </body>
    </html>
  );
}
